### ISSUE TITLE
Thickness of bottom and top plate

### ISSUE THREAD

**Issue by toniz4** [raychengy/fifi_split_keeb#3]
In the BOM there is a mention about the top plate and bottom plate. 

If I want to use it without a bottom or top plate, it would be possible? (like a gergoplex)
What would be the apropriate thickness of both of those plates? If I would make them out of arcylic or polycarbonate.

Thanks!

**Comment by hmngwy** [comment]
If acrylic, no thinner than 3mm to have sufficient durability. For the switch plate no thicker than 5mm.

**Comment by toniz4** [comment]
I'm going to build one with a 3mm acrylic, for the top and bottom plate. When i'm done i will show the results.

**Comment by rcheng-ns1** [comment]
@toniz4 sorry for the late reply! 3mm acrylic will work for the top and bottom.

**Comment by heyitscassio** [comment]
Indeed, 3mm acrylic with 6mm bottom/top  plate spacers works perfectly. Thanks!
