### ISSUE TITLE
kailh choc

### ISSUE THREAD

**Issue by rnyPlanet** [raychengy/fifi_split_keeb#6]
will it be possible to use kailh choc without hot swap? (I would try to do it myself - but I have no knowledge)

**Comment by rnyPlanet** [comment]
@estaesta @PanKnst @ray-cheng-mbi @rcheng-ns1 I saw you have knowledge and you can do something)

**Comment by rfong** [comment]
Bumping, is there any plan to support choc hotswap?

**Comment by rnyPlanet** [comment]
> 

https://github.com/pashutk/chocofi

**Comment by raychengy** [comment]
@rnyPlanet it's in my todo list, but chocofi is a great alternative for the time begin.
